version: '3.8'

services:
  soulmaskserver:
    image: keepprogress/soul-mask-docker:latest
    container_name: soulmaskserver
    restart: always
    environment:
      TZ: "Asia/Taipei"
      CHECK_UPDATE_ON_START: true
    volumes:
      - ./soulMaskSaved:/home/steam/WS/Saved
    ports:
      - 8211:8211/udp
